/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Scores,
} from './models/scores.model';

export namespace Components {
  interface PongScores {
    'scores': Scores;
  }
  interface PongWrapper {
    'name': string;
    'scores': any;
  }
}

declare global {


  interface HTMLPongScoresElement extends Components.PongScores, HTMLStencilElement {}
  var HTMLPongScoresElement: {
    prototype: HTMLPongScoresElement;
    new (): HTMLPongScoresElement;
  };

  interface HTMLPongWrapperElement extends Components.PongWrapper, HTMLStencilElement {}
  var HTMLPongWrapperElement: {
    prototype: HTMLPongWrapperElement;
    new (): HTMLPongWrapperElement;
  };
  interface HTMLElementTagNameMap {
    'pong-scores': HTMLPongScoresElement;
    'pong-wrapper': HTMLPongWrapperElement;
  }
}

declare namespace LocalJSX {
  interface PongScores extends JSXBase.HTMLAttributes<HTMLPongScoresElement> {
    'scores'?: Scores;
  }
  interface PongWrapper extends JSXBase.HTMLAttributes<HTMLPongWrapperElement> {
    'name'?: string;
    'scores'?: any;
  }

  interface IntrinsicElements {
    'pong-scores': PongScores;
    'pong-wrapper': PongWrapper;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


